# Generated by Django 4.2.5 on 2023-09-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_prediction', to='categories.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_prediction', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата прогноза')),
                ('target', models.PositiveSmallIntegerField(verbose_name='спрос в шт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='categories.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='shops.shop')),
            ],
        ),
    ]
