# Generated by Django 3.2.15 on 2023-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='forecast',
        ),
        migrations.AddField(
            model_name='forecast',
            name='date',
            field=models.DateField(default='2022-01-01', verbose_name='Прогноз на дату'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='target',
            field=models.IntegerField(default=0, verbose_name='Прогноз'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_date',
            field=models.DateField(verbose_name='Дата составления прогноза'),
        ),
    ]
