# Generated by Django 3.2.15 on 2023-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20231008_1610'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forecast',
            name='unique_forecast',
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('store', 'forecast_date', 'product', 'date'), name='unique_forecast'),
        ),
    ]
