# Generated by Django 3.2.15 on 2023-09-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id категории товара')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id группы')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcat_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id подкатегории товара')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id товара')),
                ('uom', models.PositiveSmallIntegerField(choices=[(1, 'ШТ'), (17, 'ВЕС')], verbose_name='маркер продажи на вес')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.group')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory')),
            ],
        ),
    ]
