# Generated by Django 4.2.5 on 2023-09-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('sales_type', models.PositiveSmallIntegerField(choices=[(0, 'НЕТ'), (1, 'ДА')], verbose_name='флаг наличия промо')),
                ('sales_units', models.PositiveSmallIntegerField(verbose_name='продажи без промо в шт')),
                ('sales_units_promo', models.PositiveSmallIntegerField(verbose_name='продажи c промо в шт')),
                ('sales_rub', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='продажи в рублях без промо')),
                ('sales_run_promo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='продажи в рублях промо')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='categories.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shops.shop')),
            ],
        ),
    ]
