# Generated by Django 3.2.15 on 2023-09-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sales_in_rub',
            new_name='sales_rub',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='promo_sales_in_rub',
            new_name='sales_run_promo',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales_type_id',
            new_name='sales_type',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales_in_units',
            new_name='sales_units',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='promo_sales_in_units',
            new_name='sales_units_promo',
        ),
    ]
