# Generated by Django 4.2.5 on 2023-09-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Продажи', 'verbose_name_plural': 'Продажи'},
        ),
    ]
