FROM python:3.10
RUN apt-get update && apt-get -y install cron vim
WORKDIR /ml
COPY . .
RUN pip install -r requirements.txt --no-cache-dir
COPY crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN /usr/bin/crontab /etc/cron.d/crontab
RUN echo $PYTHONPATH
# run crond as main process of container
CMD ["cron", "-f"]